# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agri_posts_development
  username: agri_posts
  password: ds20g9yB76_l
  host: localhost
  port: 5432

production:
  <<: *default
  database: agri_posts_production
  username: agri_posts
  password: ds20g9yB76_l
  host: localhost
  port: 5432
